name: 'PR Commit Check'
on:
  [pull_request]

jobs:
  check-commit-message:
    name: Check Commits
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Commits
        id: 'get-pr-commits'
        uses: tim-actions/get-pr-commits@c64db31d359214d244884dd68f971a110b29ab83
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Must be only one commit per PR
        run: |
          echo '${{ steps.get-pr-commits.outputs.commits }}' > /tmp/json
          jq '. | length' < /tmp/json > /tmp/len
          if [[ `cat /tmp/len` == 1 ]]; then exit 0; else echo "Expected 1 commit but got `cat /tmp/len`"; echo "squash to 1 commit"; echo "e.g. git rebase -i HEAD~`cat /tmp/len`"; echo "git push --force-with-lease origin ${{ github.head_ref }}  (replace "origin" with your remote, if needed)"; exit 1; fi;
          
      - name: Must use valid commit prefix
        uses: tim-actions/commit-message-checker-with-regex@v0.3.1
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}
          pattern: '^(docs|test|chore|website|ci|infra|fix|feat):\s{0,4}[^\s]+'
          error: 'Commit message must lead with a prefix from https://docs.dagger.io/1227/contributing#commit-messages / Use "feat: Add <package name> package" (without quotes) for new Universe packages / fix with `git commit -s --amend` and `git push --force-with-lease origin ${{ github.head_ref }}`  (replace "origin" with your remote, if needed) '
